DROP TABLE IF EXISTS Testing;
DROP TABLE IF EXISTS AnswerKey;
DROP TABLE IF EXISTS Answers;
DROP TABLE IF EXISTS Questions;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
    userID INTEGER PRIMARY KEY AUTOINCREMENT,
    login VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    name VARCHAR,
    surname VARCHAR,
    dateOfBirth DATE
);

CREATE TABLE Questions (
    quesID INTEGER PRIMARY KEY AUTOINCREMENT,
    quesCont TEXT UNIQUE NOT NULL
);

CREATE TABLE Answers (
    ansID INTEGER PRIMARY KEY AUTOINCREMENT,
    quesID INTEGER REFERENCES Questions (quesID) ON DELETE CASCADE,
    ansCont TEXT NOT NULL
);

CREATE TABLE AnswerKey (
    quesID INTEGER REFERENCES Questions (quesID) ON DELETE CASCADE,
    ansID INTEGER REFERENCES Answers (ansID) ON DELETE CASCADE,
    CONSTRAINT name_unique UNIQUE (quesID, ansID)
);

CREATE TABLE Testing (
    userID INTEGER REFERENCES Users (userID) ON DELETE CASCADE,
    quesID INTEGER REFERENCES Questions (quesID) ON DELETE CASCADE,
    ansID INTEGER REFERENCES Answers (ansID) ON DELETE CASCADE,
    answered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT name_unique UNIQUE (userID, quesID, ansID)
);
